#two spaces for indentation
---
  trade_file: "test_data.csv"
  futures_file: "futuresinfo.csv"
  #window color scheme
  theme:
    #three primary colors, two helper colors
    color: ["#d6ffe0","#b3ffc6","#75d18c","#affa5f","#e7f048"]
  #logic constants
  lc:
    acc: 40
    fund_mult: 1
    sig_qty: 1
  #UI constants
  dc:
    framesize-x: 650
    framesize-y: 900
    leftsize-x: 250
    UIdf: "%m/%d/%Y"
    UItf: "%H:%M"
    CSVdf: "%Y%m%d"
    CSVtf: "%H%M"